engineStrict: true
allowBuilds:
  "@parcel/watcher": true
  "@posthog/cli": true
  "@tailwindcss/oxide": true
  adapter-node-sea: true
  core-js: true
  esbuild: true
  protobufjs: true
minimumReleaseAgeExclude:
  - svelte-shaker@0.8.0
