engineStrict: true
allowBuilds:
  "@parcel/watcher": true
  "@posthog/cli": true
  "@tailwindcss/oxide": true
  adapter-node-sea: true
  better-sqlite3: true
  core-js: true
  esbuild: true
  protobufjs: true
