name: Push Checks

on:
  push:
    paths:
      - src/**
      - static/**
      - package.json
      - pnpm-lock.yaml
      - .prettierrc
      - "*.config.*s"
      - tsconfig.json
      - .github/workflows/*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest

    steps:
      - name: 📂 Checkout
        uses: actions/checkout@v6

      - name: 📥 Install pnpm
        uses: pnpm/action-setup@v5

      - name: 🧭 Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: latest
          cache: pnpm

      - name: 📥 Install NPM dependencies
        run: pnpm i

      - name: 🔍 Get modified files
        id: modified-files
        uses: tj-actions/changed-files@v47

      - name: 📤 Export results
        id: changed-files
        run: |
          code_changes=false
          config_changes=false
          deps_changes=false

          for file in ${{ steps.modified-files.outputs.all_changed_files }}; do
            if [[ $file =~ ^src/ ]] || [[ $file =~ ^static/ ]]; then
              echo "$file changes code"
              code_changes=true
            elif [[ $file = pnpm-lock.yaml ]]; then
              echo "$file changes dependencies"
              deps_changes=true
            elif [[ $file = *.config.*s ]] || [[ $file = *prettier* ]] || [[ $file = tsconfig.json ]]; then
              echo "$file changes config"
              config_changes=true
            fi
            if [[ $code_changes == 'true' && $config_changes == 'true' ]]; then
              echo "Code and config changes detected, skipping further checks"
              break
            fi
          done

          echo "code_changes=$code_changes" >> $GITHUB_OUTPUT
          echo "config_changes=$config_changes" >> $GITHUB_OUTPUT
          echo "deps_changes=$deps_changes" >> $GITHUB_OUTPUT

      - name: ✨ Check Svelte format
        id: svelte-format
        if: steps.changed-files.outputs.code_changes == 'true'
        run: pnpm check:ci

      - name: ✨ Check style with Prettier & ESLint
        id: prettier-eslint
        if: steps.changed-files.outputs.code_changes == 'true' || steps.changed-files.outputs.config_changes == 'true' || steps.changed-files.outputs.deps_changes == 'true'
        run: pnpm lint
